# Default values for surfingcat-trading-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: trading-spa
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80

mongo:
  host: mongo
