apiVersion: v1
kind: Service
metadata:
  name: {{ template "trading-spa.fullname" . }}
  labels:
    app: {{ template "trading-spa.name" . }}
    chart: {{ template "trading-spa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30201
      protocol: TCP
  selector:
    app: {{ template "trading-spa.name" . }}
